- name: app | ensure app group exists
  group: name={{ app_name }} state=present system=yes

- name: app | ensure app user exists
  user: name={{app_name}} group={{app_name}} createhome=no shell=/bin/false system=yes state=present

- name: app | copy template
  template: src=service.conf.j2 dest=/etc/init/{{ app_name }}.conf backup=yes mode=0644
  notify: restart app

- name: Create config directory
  file: path={{app_config}} state=directory

- name: app | copy app config
  template: src=config.yml.j2 dest={{ app_config }}/config.yml backup=yes mode=0644
  notify: restart app

- name: app | create dest dir for app
  file: path=/tmp/go/src/bitbucket.org/pferdefleisch/dbpm state=directory

#- name: app | sync app to remote tmp to compile remotely
  #copy: src=/Users/aaron/Go/src/bitbucket.org/pferdefleisch/dbpm/dbpm dest=/tmp/go/src/bitbucket.org/pferdefleisch/dbpm/

- name: app | go get
  shell: cd /tmp/go/src/bitbucket.org/pferdefleisch/dbpm/dbpm && GOPATH=/tmp/go /usr/local/go/bin/go get

- name: app | compile app remotely
  shell: cd /tmp/go/src/bitbucket.org/pferdefleisch/dbpm/dbpm && GOPATH=/tmp/go /usr/local/go/bin/go build -o {{app_path}}/{{app_name}} main.go
  notify: restart app

#- name: app | remove tmp app from server
  #file: path=/tmp/go/src/{{app_name}} state=absent

- name: app | cron update server with new podcasts
  cron: name="update picks" minute="0" hour="0,12" job="CONFIG={{app_config}}/config.yml {{app_path}}/{{app_name}} update"
